### ISSUE TITLE
related.js conflicts with plone.formwidget.contenttree

### ISSUE THREAD

**Issue by rafaelbco** [collective/collective.z3cform.widgets#43]
Steps to reproduce:

1. Setup a buildout containing Plone 4.3.2 and the latest released versions of collective.z3cform.widgets (1.0b9) and plone.formwidget.contenttree (1.0.7), like [this one](https://gist.github.com/rafaelbco/8976039).
2. Start Zope and create a Plone Site selecting the profiles of the two add-ons mentioned above.
3. Create two pages with titles "Doc 1" and "Doc 2".
4. The buildout also contains ZCML to activate a demo view in plone.formwidget.contenttree, named test-tree-widget. Access this view on the site root and perform *exactly* the following steps:
  1. Search for and select "Doc 1" in the first widget ("Buddy object").
  2. Click "Ok" to save.
  3. Search for and select "Doc 2" in the first widget ("Buddy object").

The problem: Now both items are selected, and there's no way to unselect one of them !

Note: it's important to execute step 4.2 (save), otherwise the problem won't show up.

I found out that if the javascript "++resource++collective.z3cform.widgets/related.js" is disabled on "portal_javascripts" then the problem does not occur.

I stopped the investigation at this point because I guess it would include debugging a lot of javascript code I'm not familiar with.

I don't know which package is blamed for this bug, but I decided to report here because plone.formwidget.contenttree is used by default for Dexterity content-types.

**Comment by rafaelbco** [comment]
Seems fixed to me on Plone 4.3.4. Should I close this ? @hvelarde

**Comment by hvelarde** [comment]
@rafaelbco be my guest :-)
