### ISSUE TITLE
Rename global javascript function: formwidget_autocomplete_new_value

### ISSUE THREAD

**Issue by kcleong** [collective/collective.z3cform.widgets#44]
For the contenttree browser (plone.formwidget.contenttree) the javascript global function 'formwidget_autocomplete_new_value' is used to update the field after an item has been selected in the contenttree overlay. I'm having problems updating a field with an existing value (see: https://github.com/plone/plone.formwidget.contenttree/issues/16).

This global function is registered by two modules in my Plone 4.3.3 buildout. The last results by ack-grep is in contenttree widget, the function is called from there for contenttree.

```
# ack --follow formwidget_autocomplete_new_value
collective/z3cform/widgets/static/related.js
3:function formwidget_autocomplete_new_value(input_box,value,label) {
64:                        formwidget_autocomplete_new_value(input_box,$(this).attr('href'),$.trim($(this).text()));

plone/formwidget/autocomplete/jquery-autocomplete/formwidget-autocomplete.js
4:        formwidget_autocomplete_new_value(input_box,data[0],data[1]);
8:function formwidget_autocomplete_new_value(input_box,value,label) {

plone/formwidget/contenttree/jquery-contenttree/contenttree.js
21:                formwidget_autocomplete_new_value(input_box,$(this).attr('href'),$.trim($(this).text()));
```

The function in collective/z3cform/widgets/static/related.js is conflicting with the one in collective.z3cform.widgets. Where is this function used from c.z3cform.widgets? Maybe it is an idea to rename the function, to prevent conflicts.

**Comment by puittenbroek** [comment]
Problem still exists due to both having the function AND the this product install it's js after that of autocomplete. Changing the order to have the 'related.js' before 'formwidget-autocmplete.js' fixes the problem. But it's unclear to me why the duplicity exsists at all?

**Comment by hvelarde** [comment]
@puittenbroek we're no longer using this package; sorry, but I can't help further.

**Comment by puittenbroek** [comment]
Well the only problem I still have is due to `collective.polls` using this package.
https://github.com/collective/collective.polls/issues/107

**Comment by hvelarde** [comment]
we can help on that :-)

**Comment by puittenbroek** [comment]
Was hoping on that ;) I'll close this issue one in favor of that issue.
